CREATE OR ALTER PROCEDURE sp_dim_Tipo_Funcionario(@data_carga DATETIME)
AS
BEGIN

    DECLARE @COD_TPO_DE_FUNCIONARIO INT
    DECLARE @NOME VARCHAR(255)

    DECLARE CUR CURSOR FOR
    SELECT
        COD_TPO_DE_FUNCIONARIO,
        NOME
    FROM
        TB_AUX_TPO_FUNCIONARIO
    WHERE
        DATA_CARGA = @data_carga

    OPEN CUR 
    FETCH NEXT FROM CUR INTO @COD_TPO_DE_FUNCIONARIO, @NOME

    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF NOT EXISTS (SELECT * FROM DIM_TPO_FUNCIONARIO WHERE COD_TPO_DE_FUNCIONARIO = @COD_TPO_DE_FUNCIONARIO)
        BEGIN
            INSERT INTO DIM_TIPO_FUNCIONARIO (COD_TPO_DE_FUNCIONARIO, NOME)
            VALUES (@COD_TPO_DE_FUNCIONARIO, @NOME)
        END
        FETCH NEXT FROM CUR INTO @COD_TPO_DE_FUNCIONARIO, @NOME
    END

    CLOSE CUR
    DEALLOCATE CUR

END

-- ---------------------------------------

EXEC sp_dim_Tipo_Funcionario '20240330'

SELECT * FROM DIM_TPO_FUNCIONARIO