CREATE OR ALTER PROCEDURE sp_dim_Funcionario(@data_carga DATETIME)
AS
BEGIN
    DECLARE @COD_FUNCIONARIO INT
    DECLARE @NOME VARCHAR(100)
    DECLARE @CPF VARCHAR(11)

    DECLARE CUR CURSOR FOR
    SELECT 
        COD_FUNCIONARIO,
        NOME,
        CPF 
    FROM 
        TB_AUX_FUNCIONARIO 
    WHERE 
        DATA_CARGA = @data_carga;

    OPEN CUR 
    FETCH NEXT FROM CUR INTO @COD_FUNCIONARIO, @NOME, @CPF

    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF NOT EXISTS (SELECT * FROM DIM_FUNCIONARIO WHERE COD_FUNCIONARIO = @COD_FUNCIONARIO)
        BEGIN
            INSERT INTO DIM_FUNCIONARIO (COD_FUNCIONARIO, NOME, CPF)
            VALUES (@COD_FUNCIONARIO, @NOME, @CPF)
        END
        FETCH NEXT FROM CUR INTO @COD_FUNCIONARIO, @NOME, @CPF
    END

    CLOSE CUR;
    DEALLOCATE CUR;
END

-- ---------------------------------------

EXEC sp_dim_Funcionario '20240330'

SELECT * FROM DIM_FUNCIONARIO

SELECT COUNT(*) FROM FATO_DIARIA