CREATE OR ALTER PROCEDURE sp_dim_funcao(@data_carga DATETIME)
AS
BEGIN
    DECLARE @COD_FUNCAO INT
    DECLARE @ANO_EXERCICIO VARCHAR(45)
    DECLARE @NOME VARCHAR(45)

    DECLARE CUR CURSOR FOR
    SELECT 
        COD_FUNCAO,
        ANO_EXERCICIO,
        NOME  
    FROM 
        TB_AUX_FUNCAO 
    WHERE
        DATA_CARGA = @data_carga;

    OPEN CUR 
    FETCH NEXT FROM CUR INTO @COD_FUNCAO, @ANO_EXERCICIO, @NOME

    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF NOT EXISTS (SELECT * FROM DIM_FUNCAO WHERE COD_FUNCAO = @COD_FUNCAO)
        BEGIN
            INSERT INTO DIM_FUNCAO (COD_FUNCAO, ANO_EXERCICIO, NOME)
            VALUES (@COD_FUNCAO, @ANO_EXERCICIO, @NOME)
        END
        FETCH NEXT FROM CUR INTO @COD_FUNCAO, @ANO_EXERCICIO, @NOME
    END

    CLOSE CUR;
    DEALLOCATE CUR;
END

-- ---------------------------------------

EXEC sp_dim_funcao '20240330'

SELECT * FROM DIM_FUNCAO