CREATE OR ALTER PROCEDURE sp_dim_Cidade(@data_carga DATETIME)
AS
BEGIN
    DECLARE @COD_CIDADE INT
    DECLARE @CIDADE VARCHAR(100)

    DECLARE CUR CURSOR FOR
    SELECT 
        COD_CIDADE,
        CIDADE 
    FROM 
        TB_AUX_CIDADE 
    WHERE 
        DATA_CARGA=@data_carga;

    OPEN CUR 
    FETCH NEXT FROM CUR INTO @COD_CIDADE, @CIDADE

    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF NOT EXISTS (SELECT * FROM DIM_CIDADE WHERE COD_CIDADE = @COD_CIDADE)
        BEGIN
            INSERT INTO DIM_CIDADE(COD_CIDADE, CIDADE)
            VALUES (@COD_CIDADE, @CIDADE)
        END
        FETCH NEXT FROM CUR INTO @COD_CIDADE, @CIDADE
    END

    CLOSE CUR;
    DEALLOCATE CUR;
END

-- ---------------------------------------

EXEC sp_dim_Cidade '20240330'

SELECT * FROM DIM_PAIS