CREATE OR ALTER PROCEDURE sp_dim_Orgao_SCDP(@data_carga DATETIME)
AS
BEGIN
	DECLARE @COD_ORGAO_SCDP INT
    DECLARE @NOME VARCHAR(255)

    DECLARE CUR CURSOR FOR
    SELECT 
        COD_ORGAO_SCDP,
        NOME
    FROM 
        TB_AUX_ORGAO_SCDP 
    WHERE 
        DATA_CARGA = @data_carga;

    OPEN CUR 
    FETCH NEXT FROM CUR INTO @COD_ORGAO_SCDP, @NOME

    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF NOT EXISTS (SELECT * FROM DIM_ORGAO_SCDP WHERE COD_ORGAO_SCDP = @COD_ORGAO_SCDP)
        BEGIN
            INSERT INTO DIM_ORGAO_SCDP (COD_ORGAO_SCDP, NOME)
            VALUES (@COD_ORGAO_SCDP, @NOME)
        END
        FETCH NEXT FROM CUR INTO @COD_ORGAO_SCDP, @NOME
    END

    CLOSE CUR;
    DEALLOCATE CUR;

END

-- ---------------------------------------

EXEC sp_dim_Orgao_SCDP '20240330'

SELECT * FROM DIM_ORGAO_SCDP