CREATE OR ALTER PROCEDURE sp_dim_Estado(@data_carga DATETIME)
AS
BEGIN
    DECLARE @COD_ESTADO INT
    DECLARE @ESTADO VARCHAR(100)
	DECLARE @SIGLA VARCHAR(2)


    DECLARE CUR CURSOR FOR
    SELECT 
        COD_ESTADO,
        ESTADO,
        SIGLA 
    FROM 
        TB_AUX_ESTADO 
    WHERE 
        DATA_CARGA = @data_carga;

    OPEN CUR 
    FETCH NEXT FROM CUR INTO @COD_ESTADO, @ESTADO, @SIGLA

    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF NOT EXISTS (SELECT * FROM DIM_ESTADO WHERE COD_ESTADO = @COD_ESTADO)
        BEGIN
            INSERT INTO DIM_ESTADO(COD_ESTADO,ESTADO,SIGLA)
            VALUES (@COD_ESTADO, @ESTADO, @SIGLA)
        END
        FETCH NEXT FROM CUR INTO @COD_ESTADO, @ESTADO, @SIGLA
    END

    CLOSE CUR;
    DEALLOCATE CUR;
END

-- ---------------------------------------

EXEC sp_dim_Estado '20240330'

SELECT * FROM DIM_ESTADO