CREATE OR ALTER PROCEDURE sp_fato_Diaria(@data_carga DATETIME)
AS
BEGIN

    DECLARE @COD_PASSAGEM INT
    DECLARE @DATA_COMPRA DATETIME 
    DECLARE @DATA_PARTIDA DATETIME
    DECLARE @DATA_CHEGADA DATETIME 
    DECLARE @QUANTIDADE_DIARIAS INT
    DECLARE @VALOR NUMERIC(10,2)
    DECLARE @COD_CIDADE_ORIGEM INT
    DECLARE @COD_CIDADE_DESTINO INT
    DECLARE @COD_ESTADO_ORIGEM INT
    DECLARE @COD_ESTADO_DESTINO INT
    DECLARE @COD_PAIS_ORIGEM INT
    DECLARE @COD_PAIS_DESTINO INT
    DECLARE @COD_FUNCIONARIO INT 
    DECLARE @COD_ORGAO_SCDP INT 
    DECLARE @COD_MEIO_DE_TRANSPORTE INT 
    DECLARE @COD_TPO_DE_VIAGEM INT
    DECLARE @COD_MOTIVO_VIAGEM INT

    DECLARE @ID_DATA_COMPRA INT 
    DECLARE @ID_DATA_PARTIDA INT 
    DECLARE @ID_DATA_CHEGADA INT 
    DECLARE @ID_CIDADE_ORIGEM INT 
    DECLARE @ID_CIDADE_DESTINO INT 
    DECLARE @ID_ESTADO_ORIGEM INT 
    DECLARE @ID_ESTADO_DESTINO INT
    DECLARE @ID_PAIS_ORIGEM INT 
    DECLARE @ID_PAIS_DESTINO INT
    DECLARE @ID_FUNCIONARIO INT 
    DECLARE @ID_ORGAO_SCDP INT 
    DECLARE @ID_MEIO_DE_TRANSPORTE INT
    DECLARE @ID_TPO_DE_VIAGEM INT 
    DECLARE @ID_MOTIVO_VIAGEM INT


    DECLARE CUR CURSOR FOR
    SELECT
        COD_PASSAGEM,
        DATA_COMPRA,
        DATA_PARTIDA,
        DATA_CHEGADA,
        QUANTIDADE_DIARIAS,
        VALOR,
        COD_CIDADE_ORIGEM,
        COD_CIDADE_DESTINO,
        COD_ESTADO_ORIGEM,
        COD_ESTADO_DESTINO,
        COD_PAIS_ORIGEM,
        COD_PAIS_DESTINO
        COD_FUNCIONARIO,
        COD_ORGAO_SCDP,
        COD_MEIO_DE_TRANSPORTE,
        COD_TPO_DE_VIAGEM,
        COD_MOTIVO_VIAGEM
    FROM
        TB_AUX_DIARIA
    WHERE
        DATA_CARGA = @data_carga

    OPEN CUR
    FETCH NEXT FROM CUR INTO @COD_PASSAGEM, @DATA_COMPRA, @DATA_PARTIDA, @DATA_CHEGADA, @QUANTIDADE_DIARIAS, @VALOR, @COD_CIDADE_ORIGEM, @COD_CIDADE_DESTINO, @COD_ESTADO_ORIGEM, @COD_ESTADO_DESTINO, @COD_PAIS_ORIGEM, @COD_PAIS_DESTINO, @COD_FUNCIONARIO, @COD_ORGAO_SCDP, @COD_MEIO_DE_TRANSPORTE, @COD_TPO_DE_VIAGEM, @COD_MOTIVO_VIAGEM

    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @ID_DATA_COMPRA = NULL 
        SET @ID_DATA_PARTIDA = NULL 
        SET @ID_DATA_CHEGADA = NULL 
        SET @ID_CIDADE_ORIGEM = NULL 
        SET @ID_CIDADE_DESTINO = NULL 
        SET @ID_ESTADO_ORIGEM = NULL 
        SET @ID_ESTADO_DESTINO = NULL
        SET @ID_PAIS_ORIGEM = NULL 
        SET @ID_PAIS_DESTINO = NULL
        SET @ID_FUNCIONARIO = NULL 
        SET @ID_ORGAO_SCDP = NULL 
        SET @ID_MEIO_DE_TRANSPORTE = NULL
        SET @ID_TPO_DE_VIAGEM = NULL 
        SET @ID_MOTIVO_VIAGEM = NULL


        SELECT @ID_DATA_COMPRA = ID_TEMPO
        FROM DIM_TEMPO
        WHERE DATA = @DATA_COMPRA AND NIVEL = 'DIA'


        SELECT @ID_DATA_PARTIDA = ID_TEMPO
        FROM DIM_TEMPO
        WHERE DATA = @DATA_PARTIDA AND NIVEL = 'DIA'


        SELECT @ID_DATA_CHEGADA = ID_TEMPO
        FROM DIM_TEMPO
        WHERE DATA = @DATA_CHEGADA AND NIVEL = 'DIA'


        SELECT @ID_CIDADE_ORIGEM = ID_CIDADE
        FROM DIM_CIDADE
        WHERE COD_CIDADE = @COD_LOCAL_ORIGEM


        SELECT @ID_CIDADE_DESTINO = ID_CIDADE
        FROM DIM_CIDADE
        WHERE COD_CIDADE = @COD_LOCAL_DESTINO


        SELECT @ID_ESTADO_ORIGEM = e.ID_ESTADO
        FROM DIM_CIDADE c
        INNER JOIN DIM_ESTADO e ON (c.COD_ESTADO = e.COD_ESTADO)
        WHERE COD_CIDADE = @COD_LOCAL_ORIGEM


        FETCH NEXT FROM CUR INTO @COD_PASSAGEM, @DATA_COMPRA, @DATA_PARTIDA, @DATA_CHEGADA, @QUANTIDADE_DIARIAS, @VALOR, @COD_CIDADE_ORIGEM, @COD_CIDADE_DESTINO, @COD_ESTADO_ORIGEM, @COD_ESTADO_DESTINO, @COD_PAIS_ORIGEM, @COD_PAIS_DESTINO, @COD_FUNCIONARIO, @COD_ORGAO_SCDP, @COD_MEIO_DE_TRANSPORTE, @COD_TPO_DE_VIAGEM, @COD_MOTIVO_VIAGEM
    END

    CLOSE CUR
    DEALLOCATE CUR 
END

-- -------------------------------

EXEC sp_fato_Diaria '20240330'

SELECT * FROM FATO_DIARIA