CREATE OR ALTER PROCEDURE sp_dim_Motivo_Viagem(@data_carga DATETIME)
AS
BEGIN
    DECLARE @COD_MOTIVO_VIAGEM INT
    DECLARE @NOME VARCHAR(255)

    DECLARE CUR CURSOR FOR
    SELECT 
        COD_MOTIVO_VIAGEM,
        NOME
    FROM 
        TB_AUX_MOTIVO_VIAGEM 
    WHERE 
        DATA_CARGA = @data_carga

    OPEN CUR 
    FETCH NEXT FROM CUR INTO @COD_MOTIVO_VIAGEM, @NOME

    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF NOT EXISTS (SELECT * FROM DIM_MOTIVO_VIAGEM WHERE COD_MOTIVO_VIAGEM = @COD_MOTIVO_VIAGEM)
        BEGIN
            INSERT INTO DIM_MOTIVO_VIAGEM(COD_MOTIVO_VIAGEM, NOME)
            VALUES (@COD_MOTIVO_VIAGEM, @NOME)
        END
        FETCH NEXT FROM CUR INTO @COD_MOTIVO_VIAGEM, @NOME
    END

    CLOSE CUR;
    DEALLOCATE CUR;
END

-- ---------------------------------------

EXEC sp_dim_Motivo_Viagem '20240330'

SELECT * FROM DIM_MOTIVO_VIAGEM