-- --------------------------------------------------------

--
-- Estrutura para tabela `CIDADE`
--

CREATE TABLE TB_PAIS (
  COD_PAIS INT NOT NULL PRIMARY KEY,
  PAIS VARCHAR(100) NOT NULL
)

CREATE TABLE TB_ESTADO (
	COD_ESTADO INT NOT NULL PRIMARY KEY,
	ESTADO VARCHAR(100) NOT NULL,
	SIGLA VARCHAR(2) NOT NULL,
)

CREATE TABLE TB_CIDADE (
	COD_CIDADE INT NOT NULL PRIMARY KEY,
	CIDADE VARCHAR(100) NOT NULL,
)
-- --------------------------------------------------------

--
-- Estrutura para tabela `Funcao`
--

CREATE TABLE TB_FUNCAO (
  COD_FUNCAO INT NOT NULL PRIMARY KEY,
  ANO_EXERCICIO INT NOT NULL,
  NOME VARCHAR(45) NOT NULL,
)
-- --------------------------------------------------------

--
-- Estrutura para tabela `Tipo de FUNCIONARIO`
--

CREATE TABLE TB_TPO_FUNCIONARIO(
  COD_TPO_DE_VIAGEM INT NOT NULL PRIMARY KEY,
  NOME VARCHAR(255) NOT NULL
)

-- --------------------------------------------------------

--
-- Estrutura para tabela `CARGO`
--

CREATE TABLE TB_CARGO (
  COD_CARGO INT NOT NULL PRIMARY KEY,
  NOME VARCHAR(45) NOT NULL,
)
-- --------------------------------------------------------

--
-- Estrutura para tabela `Funcionario`
--

CREATE TABLE TB_FUNCIONARIO (
  COD_FUNCIONARIO INT NOT NULL PRIMARY KEY,
  NOME VARCHAR(45) NOT NULL,
  SOBRENOME VARCHAR(45) NOT NULL,
  CPF VARCHAR(11) NOT NULL,
  COD_FUNCAO INT NOT NULL,
  COD_TIPO_FUNCIONARIO INT NOT NULL,
  COD_CARGO INT NOT NULL,
  CONSTRAINT FK_FUNCAO FOREIGN KEY (COD_FUNCAO) REFERENCES TB_FUNCAO (COD_FUNCAO),
  CONSTRAINT FK_TIPO_FUNCIONARIO FOREIGN KEY (COD_TIPO_FUNCIONARIO) REFERENCES TB_TPO_FUNCIONARIO (COD_TIPO_FUNCIONARIO),
  CONSTRAINT FK_CARGO FOREIGN KEY (COD_CARGO) REFERENCES TB_CARGO (COD_CARGO)
)

CREATE INDEX CPF_FUN_INDEX ON TB_FUNCIONARIO (CPF);
-- --------------------------------------------------------

--
-- Estrutura para tabela `Orgão SCDP`
--

CREATE TABLE TB_ORGAO_SCDP (
  COD_ORGAO_SCDP INT NOT NULL PRIMARY KEY,
  NOME VARCHAR(45) NOT NULL,
 
)
-- --------------------------------------------------------

--
-- Estrutura para tabela `Meio de transporte`
--

CREATE TABLE TB_MEIO_DE_TRANSPORTE(
  COD_MEIO_DE_TRANSPORTE INT NOT NULL PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL
)

-- --------------------------------------------------------

--
-- Estrutura para tabela `Motivo da Viagem`
--

CREATE TABLE TB_MOTIVO_VIAGEM(
  COD_MOTIVO_VIAGEM INT NOT NULL PRIMARY KEY,
  NOME VARCHAR(255) NOT NULL
)

-- --------------------------------------------------------

--
-- Estrutura para tabela `Tipo de viagem`
--

CREATE TABLE TB_TPO_DE_VIAGEM(
  COD_TPO_DE_VIAGEM INT NOT NULL PRIMARY KEY,
  NOME VARCHAR(255) NOT NULL
)

-- --------------------------------------------------------

--
-- Estrutura para tabela `Passagem`
--

CREATE TABLE TB_DIARIA (
  COD_PASSAGEM INT NOT NULL PRIMARY KEY,
  DATA_COMPRA DATETIME NOT NULL,
  DATA_PARTIDA DATETIME NOT NULL,
  DATA_CHEGADA DATETIME NOT NULL,
  QUANTIDADE_DIARIAS INT NOT NULL,
  VALOR NUMERIC(10,2) NOT NULL,
  COD_CIDADE_ORIGEM INT,
  COD_CIDADE_DESTINO INT,
  COD_ESTADO_ORIGEM INT,
  COD_ESTADO_DESTINO INT,
  COD_PAIS_ORIGEM INT,
  COD_PAIS_DESTINO INT,
  COD_FUNCIONARIO INT NOT NULL,
  COD_ORGAO_SCDP INT NOT NULL,
  COD_MEIO_DE_TRANSPORTE INT NOT NULL,
  COD_TPO_DE_VIAGEM INT NOT NULL,
  COD_MOTIVO_VIAGEM INT NOT NULL,
  CONSTRAINT FK_CIDADE_ORIGEM FOREIGN KEY (COD_LOCAL_ORIGEM) REFERENCES TB_CIDADE (COD_LOCAL_ORIGEM),
  CONSTRAINT FK_CIDADE_DESTINO FOREIGN KEY (COD_LOCAL_DESTINO) REFERENCES TB_CIDADE (COD_LOCAL_DESTINO),
  CONSTRAINT FK_ESTADO_ORIGEM FOREIGN KEY (COD_ESTADO_ORIGEM) REFERENCES TB_ESTADO (COD_ESTADO_ORIGEM),
  CONSTRAINT FK_ESTADO_DESTINO FOREIGN KEY (COD_ESTADO_DESTINO) REFERENCES TB_ESTADO (COD_ESTADO_DESTINO),
  CONSTRAINT FK_PAIS_ORIGEM FOREIGN KEY (COD_PAIS_ORIGEM) REFERENCES TB_PAIS (COD_PAIS_ORIGEM),
  CONSTRAINT FK_PAIS_DESTINO FOREIGN KEY (COD_PAIS_DESTINO) REFERENCES TB_PAIS (COD_PAIS_DESTINO),
  CONSTRAINT FK_FUNCIONARIO FOREIGN KEY (COD_FUNCIONARIO) REFERENCES TB_FUNCIONARIO (COD_FUNCIONARIO),
  CONSTRAINT FK_ORGAO_SCDP FOREIGN KEY (COD_ORGAO_SCDP) REFERENCES ORGAO_SCDP (COD_ORGAO_SCDP),
  CONSTRAINT FK_MEIO_DE_TRANSPORTE FOREIGN KEY (COD_MEIO_DE_TRANSPORTE) REFERENCES TB_MEIO_DE_TRANSPORTE (COD_MEIO_DE_TRANSPORTE),
  CONSTRAINT FK_TIPO_VIAGEM FOREIGN KEY (COD_TPO_DE_VIAGEM) REFERENCES TB_TPO_DE_VIAGEM (COD_TPO_DE_VIAGEM),
  CONSTRAINT FK_MOTIVO_VIAGEM FOREIGN KEY (COD_MOTIVO_VIAGEM) REFERENCES TB_MOTIVO_VIAGEM (COD_MOTIVO_VIAGEM),
)


-- --------------------------------------------------------

