--PROCEDURE OKAY
CREATE TABLE TB_AUX_PAIS (
    DATA_CARGA DATETIME NOT NULL,
    COD_PAIS INT NOT NULL,
    PAIS VARCHAR(100) NOT NULL
)

--PROCEDURE OKAY
CREATE TABLE TB_AUX_ESTADO (
    DATA_CARGA DATETIME NOT NULL,
	COD_ESTADO INT NOT NULL,
	ESTADO VARCHAR(100) NOT NULL,
	SIGLA VARCHAR(2) NOT NULL,
)

--PROCEDURE OKAY
CREATE TABLE TB_AUX_CIDADE (
    DATA_CARGA DATETIME NOT NULL,
	COD_CIDADE INT NOT NULL,
	CIDADE VARCHAR(100) NOT NULL,
)

--PROCEDURE OKAY
CREATE TABLE TB_AUX_FUNCAO (
    DATA_CARGA DATETIME NOT NULL,
    COD_FUNCAO INT NOT NULL,
    ANO_EXERCICIO VARCHAR(45) NOT NULL,
    NOME VARCHAR(45) NOT NULL,
)

--PROCEDURE OKAY
CREATE TABLE  TB_AUX_TPO_FUNCIONARIO(
    DATA_CARGA DATETIME NOT NULL,
    COD_TPO_DE_VIAGEM INT NOT NULL,
    NOME VARCHAR(255) NOT NULL
)

--PROCEDURE OKAY
CREATE TABLE TB_AUX_CARGO (
    DATA_CARGA DATETIME NOT NULL,
    COD_CARGO INT NOT NULL,
    NOME VARCHAR(45) NOT NULL
)

--PROCEDURE OKAY
CREATE TABLE TB_AUX_FUNCIONARIO (
    DATA_CARGA DATETIME NOT NULL,
    COD_FUNCIONARIO INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    COD_FUNCAO INT NOT NULL,
    COD_TIPO_FUNCIONARIO INT NOT NULL,
    COD_CARGO INT NOT NULL,
)

--PROCEDURE OKAY
CREATE TABLE TB_AUX_ORGAO_SCDP (
    DATA_CARGA DATETIME NOT NULL,
    COD_ORGAO_SCDP INT NOT NULL,
    NOME VARCHAR(45) NOT NULL,
)

--PROCEDURE OKAY
CREATE TABLE TB_AUX_MEIO_DE_TRANSPORTE(
    DATA_CARGA DATETIME NOT NULL,
    COD_MEIO_DE_TRANSPORTE INT NOT NULL,
    NOME VARCHAR(100) NOT NULL
)

--PROCEDURE OKAY
CREATE TABLE TB_AUX_MOTIVO_VIAGEM(
    DATA_CARGA DATETIME NOT NULL,
    COD_MOTIVO_VIAGEM INT NOT NULL,
    NOME VARCHAR(255) NOT NULL
)

--PROCEDURE OKAY
CREATE TABLE TB_AUX_TPO_DE_VIAGEM(
    DATA_CARGA DATETIME NOT NULL,
    COD_TPO_DE_VIAGEM INT NOT NULL,
    NOME VARCHAR(255) NOT NULL
)

--PROCEDURE OKAY
/*Atentar a mudan�a na vari�vel qtDiarias conforme pedido por andr�*/ 
CREATE TABLE TB_AUX_DIARIA (
    DATA_CARGA DATETIME NOT NULL,
    COD_PASSAGEM INT NOT NULL,
    DATA_COMPRA DATETIME NOT NULL,
    DATA_PARTIDA DATETIME NOT NULL,
    DATA_CHEGADA DATETIME NOT NULL,
    QUANTIDADE_DIARIAS INT NOT NULL,
    VALOR NUMERIC(10,2) NOT NULL,
    COD_LOCAL_ORIGEM INT NOT NULL,
    COD_LOCAL_DESTINO INT NOT NULL,
    COD_FUNCIONARIO INT NOT NULL,
    COD_ORGAO_SCDP INT NOT NULL,
    COD_MEIO_DE_TRANSPORTE INT NOT NULL,
    COD_TPO_DE_VIAGEM INT NOT NULL,
    COD_MOTIVO_VIAGEM INT NOT NULL,
);


