create or alter procedure sp_oltp_diaria(@data_carga datetime)
as
begin
    DELETE FROM TB_AUX_DIARIA
	WHERE DATA_CARGA = @data_carga;

    INSERT INTO TB_AUX_DIARIA
    SELECT 
      @data_carga, 
      D.COD_DIARIA,
      D.DATA_COMPRA,
      D.DATA_PARTIDA,
      D.DATA_CHEGADA,
      D.QUANTIDADE_DIARIAS,
      D.VALOR,
      D.COD_CIDADE_ORIGEM,
      D.COD_CIDADE_DESTINO,
      CO.COD_ESTADO AS COD_ESTADO_ORIGEM,
      CD.COD_ESTADO AS COD_ESTADO_DESTINO,
      PO.COD_PAIS AS COD_PAIS_ORIGEM,
      PD.COD_PAIS AS COD_PAIS_DESTINO,
      D.COD_FUNCIONARIO,
      D.COD_ORGAO_SCDP,
      D.COD_MEIO_DE_TRANSPORTE,
      D.COD_TIPO_DE_VIAGEM,
      F.COD_TIPO_FUNCIONARIO,
      D.COD_MOTIVO_VIAGEM
    FROM 
      TB_DIARIA D
    INNER JOIN
      TB_FUNCIONARIO F ON D.COD_FUNCIONARIO = F.COD_FUNCIONARIO
    INNER JOIN 
		  TB_CIDADE CO ON D.COD_CIDADE_ORIGEM = CO.COD_CIDADE
    INNER JOIN 
		  TB_ESTADO EO ON CO.COD_ESTADO = EO.COD_ESTADO
    INNER JOIN 
		  TB_PAIS PO ON EO.COD_PAIS = PO.COD_PAIS
    INNER JOIN 
		  TB_CIDADE CD ON D.COD_CIDADE_DESTINO = CD.COD_CIDADE
    INNER JOIN 
		  TB_ESTADO ED ON CD.COD_ESTADO = ED.COD_ESTADO
    INNER JOIN 
		  TB_PAIS PD ON ED.COD_PAIS = PD.COD_PAIS;
	
end


-- ---------------------------------------

EXEC sp_oltp_diaria '20240330'

SELECT * FROM TB_AUX_DIARIA